### ISSUE TITLE
Include annotations in the existing UK Average house price chart

### ISSUE THREAD

**Issue by Pablo-tester** [Pablo-tester/house_market#32]
We want to include annotations as horizontal lines for the COVID-19 lock-downs and specific custom shaped annotations to indicate house price, date and house to income ratio metric next to specific dates in the UK average house price chart

**Comment by Pablo-tester** [comment]
Actions required to close this issue: 

1. Update existing data and chart to include November 2023 UK House price (latest data release by ONS)
2. In the ggplot2 line charts created for median uk house price and also for monthly and yearly price variation: Include in the plot the last value of each line as label.

**Comment by Pablo-source** [comment]
Included 2023 Nov data
