### ISSUE TITLE
Provide new script for EDA of housing data

### ISSUE THREAD

**Issue by Pablo-tester** [Pablo-tester/house_market#9]
Add new script to transform initial date variables into R formatted dates and create two plots to display metrics (Average House price and Annual house price change)

**Comment by Pablo-tester** [comment]
All changes will be applied by @Pablo-source creating a new branch for this feature and requesting a pull request upon completion

**Comment by Pablo-source** [comment]
I have read this Issue details and I will start by cloning this repo  from Pablo-tester and created a new branch to introduce this new development the branch  is going to be called "Housing_data_EDA"
